lane :test do
  # 1.
  xcodebuild(
    workspace: "TestProject/TestProject.xcworkspace",    
    clean: true,
    build: true,
    scheme: "TestProject",
    destination: "generic/platform=iOS",
    build_settings: {
      "CODE_SIGNING_REQUIRED" => "NO",
      "CODE_SIGN_IDENTITY" => "",
      "OTHER_SWIFT_FLAGS" => "-Xfrontend -debug-time-function-bodies"
    },
    buildlog_path: "fastlane/logs"
  )
  
  # 2.
  compilation_time_report(time_limit: 0.00, source_pathes: ["TestProject"], xcodebuild_log_path: "fastlane/logs/xcodebuild.log")
end
